### ISSUE TITLE
Some wrong results, may just need an error

### ISSUE THREAD

**Issue by csaid** [dodger487/dplython#13]
Hi Chris R.

Thank you for making such a useful library. I'm really looking forward to using this!

There were a couple of things I tried on a lark, kind of hoping that they might work, but which gave me "wrong" results. I kind of expected these wouldn't work, but I think getting an error might be better. Of course it would be even more amazing if they magically worked as expected :) although I'm guessing that would be very hard or even impossible to implement.

``` python
# I tried to pass an if-else expression as the value in mutate()
# The results only used the color column, but not clarity column
diamonds = diamonds >> mutate(conditional_results = X.color if X.cut == "Premium" else X.clarity)

# I tried including an "or" in dfilter, but this only returned premium diamonds.
premium_and_ideal = diamonds >> dfilter(X.cut == "Premium" or X.cut == "Ideal")
```

**Comment by dodger487** [comment]
Hi Chris,
So glad you like the package and thank you for helping it by opening an issue.

For your first question, I agree that the current result is wrong-- dplython should either do the right thing or throw an error. I'm going to have to take a deeper look later, but for now I'll say that this is an important behavior (I used this in R a day or two ago!) and I would like to support it in dplython.

You can use an "or" in dfilter, but it has to be the bitwise or (aka | ) and not the logical or. This is similar to the behavior in pandas, such as:

``` python
premium_and_ideal_pd = diamonds[(diamonds.cut == "Premium") | (diamonds.cut == "Ideal")]
premium_and_ideal_dp = diamonds >> dfilter((X.cut == "Premium") | (X.cut == "Ideal"))
```

In python, `or` and `and` have special short-circuiting properties which means that you can't override them. I will update the README to make this more clear (and hopefully soon add more documentation overall).

**Comment by dodger487** [comment]
For your first question with the conditional result, you can use a "Later" function. You lose the if-else syntax, but I'm not sure if it's possible to use the if-else syntax in this case. Something like this works when I'm testing it out though:

``` python
@DelayFunction
def IfElse(bool_series, series_true, series_false):
  index = bool_series.index
  newSeries = pandas.Series([s1 if b else s2 for b, s1, s2 
      in zip(bool_series, series_true, series_false)])
  newSeries.index = index
  return newSeries

foo = diamonds >> mutate(conditional_results = IfElse(X.cut == "Premium", X.color, X.clarity))
foo >> select(X.cut, X.color, X.clarity, X.conditional_results) >> head()
"""
Out:
       cut color clarity conditional_results
0    Ideal     E     SI2                 SI2
1  Premium     E     SI1                   E
2     Good     E     VS1                 VS1
3  Premium     I     VS2                   I
4     Good     J     SI2                 SI2
"""
```

**Comment by dodger487** [comment]
With #38, this now throws a `ValueError` when trying to call `__nonzero__` on a `Later`. So these examples should now throw errors.

I've also added the if-else function to the package as a function `if_else`.
