### ISSUE TITLE
Drop support for python 2.6

### ISSUE THREAD

**Issue by Nagasaki45** [dodger487/dplython#2]
Running your test suite after `python setup.py install` on a clean python 2.6 virtualenv fails. The failure occurs when importing pandas, as the latest pandas version (0.18.0) doesn't support python 2.6 anymore. Therefore, I think that it is legitimate to drop support for python 2.6 in this project as well.

**Comment by dodger487** [comment]
Yeah, that makes sense. Dropping support for 2.6 in https://github.com/dodger487/dplython/commit/817c9ae9991122ef3596ba6f754e08f8e4118674
