### ISSUE TITLE
Better str for Later object

### ISSUE THREAD

**Issue by dodger487** [dodger487/dplython#24]
There's no "str" for a Later object right now. This makes it hard to interactively see what's going on. It also makes it more difficult to debug or know what a particular Later is. If we have this feature, it could enable other nice features! For example, dplyr does a nice job with this. As mentioned in #23, if you do something like `df %>% mutate(x + 7)` the output will be a dataframe with a column named `x + 7`.

It would be great to have a **str** method on a Later that could show you the expression that was written. So:

``` python
foo = X.x + X.y.mean()**2
str(foo)
# returns "X.x + X.y.mean()**2"
```

**Comment by danrobinson** [comment]
I'd drop the `X`s and maybe the `()`s in the string expression: `x + y.mean**2`

**Comment by dodger487** [comment]
I've added a good start to str methods with #31. 

Here's a repeat of my notes from the PR:
This adds a good base `__str__` method to Later objects. The idea is to give strings that could be plugged into an interpreter to give the result of the Later.

``` python
str(X.x.mean())
# 'data["x"].mean()'
```

Currently, this always uses a fake variable named `data`. This could be something else, like `df` or `DATA`, or something user-specified, but I like trying to keep this simpler, at least for the first pull.

There is, however, more work to be done. In particular, this always uses magic method names instead of operators. For example:

``` python
str(X.x + X.y)
# 'data["x"].__add__(data["y"])
```

It may be possible to look at the Python internals to see when a user used `+` or `__add__`. For example, see [this link](http://stackoverflow.com/questions/36557885/know-if-or-add-called-on-an-object/36558305?noredirect=1#comment60727625_36558305). I believe we'll need to make a mapping of all magic methods to their operators.

Another issue is that when using this in the ipython interpreter, sometimes methods or attributes are called behind the scenes on your object, which stick around on the Later:

``` python
In [4]: foo = X.x.mean()

In [5]: foo
Out[5]: data["x"].mean()._ipython_display_._ipython_canary_method_should_not_exist_
```

These should be fixed in the future, but I think this is a good start to make Laters easier to use and debug.

**Comment by dodger487** [comment]
If anyone is looking to get involved with writing code, this could be a great place to start!

**Comment by dodger487** [comment]
#48 and #37 finish this up
