### ISSUE TITLE
Rename dfilter to filter

### ISSUE THREAD

**Issue by danrobinson** [dodger487/dplython#27]
As I suggested in #22, I think we could safely "overload" the built-in `filter` function by testing whether it is called with a callable and an iterable in that order. Since neither DplyFrames nor DataFrames are callable, I think we'll be safe.

**Comment by ngould** [comment]
Overloading filter() would be one more thing to grok when using dplython for the first time. If it's just called dfilter, there is no ambiguity. 

My guess is that developers using dplython as part of some other software project would not get as far as reading docs or code to determine that dplython's filter() is overloaded. They would just do `from dplython import filter as dfilter` or something like that, to ensure beyond any doubt that there will be no unexpected behavior.

So I'm for keeping it as it is.

**Comment by danrobinson** [comment]
I think having to remember `dfilter` is a lot more cognitive overhead. 

I also think it'll be pretty rare that people want to use the built-in `filter` function in the same file as they've imported `filter` from dplython. 

For one thing, the main use case for dplython is probably exploratory data analysis, where ownership of a particular file is likely to be limited to one or only a few people.

For another, the built-in `filter` is pretty obscure, since it can always be done with a list comprehension, which is usually [more pythonic](http://google-styleguide.googlecode.com/svn/trunk/pyguide.html). Guido van Rossum actually [argued](http://www.artima.com/weblogs/viewpost.jsp?thread=98196) that `filter` should be dropped from Python 3. As an unscientific obscurity test, I [searched "filter" in Python files on GitHub](https://github.com/search?l=Python&p=1&q=filter&type=Code&utf8=%E2%9C%93), and the vast majority of results weren't referring to the built-in.

Finally, I think people can reasonably expect dplython's `filter` to safely overload the built-in, since it would be a bug if it behaved otherwise.

So the only cognitive overhead is for people who 1) know that filter is a Python built-in, but 2) don't know that list comprehensions are preferred, but 3) do care about overriding built-ins, but 4) don't care enough to check the docs, but 5) care too much to trust the package. And, like you said, those people can just `import dplython` or `from dplython import filter as dfilter`.

**Comment by ngould** [comment]
I agree with your reasons for wanting to do this, but I still think the pros are outweighed by the cons. Overriding builtins is just not done in polite society. People would see that we have overridden filter and have a ["WTF?"](http://www.osnews.com/story/19266/WTFs_m) moment. That would be bad for the perception of dplython as a professional quality project.

The reason overriding is not appreciated is because it can lead to very subtle bugs. E.g., builtin functions have a different type than other functions. So overriding can mess up any code that is dependent on types.

Do you know of any Python packages with decent adoption that override builtins? (That is a non-rhetorical question, and also a challenge if you care enough to support your case here.)

**Comment by dodger487** [comment]
What about trying to avoid this issue by giving an entirely different name, like `winnow`, `filtrate`, `sift`, `refine`, `comb`, or `clean`? I don't like the idea of overriding `filter`, but `dfilter` isn't a word and I often screw it up when writing it. I think `sift` is pretty good.

**Comment by danrobinson** [comment]
Good idea! I like `winnow`, `filtrate`, and `sift`.

My personal preference would be to use method chaining instead of `>>`ing, which would avoid this issue (though it would raise others). But that'd be a separate thread.

**Comment by dodger487** [comment]
Alright, I'm going to change `dfilter` to `sift`. I think `sift` is the most popular word and has the right meaning, and 

Note that this breaks code people have written already with pandas. The current goal is to find issues like this, fix them, and then maintain backwards compatibility with a release 0.1 going forward.

**Comment by danrobinson** [comment]
Why not have `dfilter` as an alias to `sift`? It can raise a DeprecationWarning.

**Comment by dodger487** [comment]
Good call, added that.
