### ISSUE TITLE
Missing column selection verbs rename and transmute

### ISSUE THREAD

**Issue by dgrtwo** [dodger487/dplython#40]
`select` and `mutate` are present, but there are two others that are variations on these:
- `rename` is like `select`, but leaves other columns as they are: `diamonds >> rename(Price = price)` will just rename the one column.
- `transmute` is like `select`, but allows mutation in column definitions, e.g. `diamonds >> transmute(carat, new_price = price / 1000)` will have only two columns, with `new_price` manipulated

**Comment by dodger487** [comment]
These are added with #43 and #42
