### ISSUE TITLE
Missing count

### ISSUE THREAD

**Issue by dgrtwo** [dodger487/dplython#41]
Count the number of unique combinations of columns with `diamonds >> count(X.color, X.cut)`, creating a new column called `n`.

(Of the missing dplyr verbs, I think this is the single most important; it's one of the most frequent ones I use. It can be imitated with `>> group_by(X.color, X.cut) >> summarize(n = X._.nrow())`) (or whatever nrow equivalent is, but this is especially awkward until we have a `n()`-like solution)

**Comment by dodger487** [comment]
Completed in #50
