### ISSUE TITLE
No ordering of mutate kwargs arguments

### ISSUE THREAD

**Issue by dodger487** [dodger487/dplython#6]
As uncovered in https://github.com/dodger487/dplython/issues/5.

In Dplyr, the user is able to add a column in a mutate statement derived from a column that he or she just wrote. I want to make this feature available in dplython. So:
`diamonds_dp = self.diamonds >> mutate(foo=X.x, bar=X.foo.mean())`
should be valid. foo should be the first column added, followed by bar. 

This is difficult to accomplish though as python throws away the order information of *_kwargs. Currently, this example code would sometimes work and sometimes not work depending on the dictionary ordering of *_kwargs. There's a PEP out to accomplish this (https://www.python.org/dev/peps/pep-0468/) but it doesn't look like this feature is currently supported.

In a bad case, this will mean the user doesn't know what order to expect columns to be in. In a worse case, this will inconsistently cause errors when a use tries to create a column derived from another one.

Some potential solutions, none of which seem great:
- Restrict mutate statements to one additional column per mutate (yuck)
- Sort the dictionary in some way, like alphabetical
- Examine each added Later to see if it derives from a column that isn't yet present in the DataFrame, add these last.
- Something else?

**Comment by has2k1** [comment]
Under the "something else?" brainstorm,

Change the function signature to `mutate(*args, **kwargs)` and `args` would be ordered tuples or a single sequence of tuples.

``` python
diamonds_dp = self.diamonds >> mutate([('foo', X.x), ('bar', X.foo.mean())])
```

One of the `todos` is about allowing string column names, so the first elements of each tuple should not be a problem. But there is still the issue of `X.foo` being unavailable at function call time but there could be another API change to remedy it.

**Comment by dodger487** [comment]
@has2k1 that looks like a reasonable albeit not ideal solution. I think I prefer not having the argument be a list, but rather each argument is a tuple, e.g.
`diamonds = diamonds >> mutate(('foo', X.x), ('bar', X.foo.mean())`
There should be no issue with `X.foo.mean()` being available at call time, as the `foo` column will have been created by that point.

Another idea is to add in an optional `enforce_ordering` argument which will tell dplython which order in which to add the columns. For example:
`diamonds = diamonds >> mutate(bar=X.foo, foo=X.x, enforce_ordering=["foo", "bar"])`
This means you can't add a column named `enforce_ordering` though...

These don't need to be mutually exclusive either-- we could add all of them. I'm curious what everyone thinks is best. I'm leaning towards just using an "enforce order" argument along with **kwargs.

**Comment by dodger487** [comment]
Another issue is that python disallows repeated keywords, so:
`diamonds >> mutate(foo=X.x, foo=X.foo/2)`
chokes with a 
`SyntaxError: keyword argument repeated`
This is something that _is_ allowed in dplyr.

The `*args` solution of passing tuples would avoid that problem.

**Comment by dodger487** [comment]
I've been leaning towards adding a default ordering of alphabetical, along with a an `_enforce_order` keyword which could be a list of keys in the user's desired order. While looking through pandas documentation, I saw that for the `assign` call they use alphabetical order:

## Notes

Since `kwargs` is a dictionary, the order of your
arguments may not be preserved. The make things predicatable,
the columns are inserted in alphabetical order, at the end of
your DataFrame. Assigning multiple columns within the same
`assign` is possible, but you cannot reference other columns
created within the same `assign` call.

**Comment by has2k1** [comment]
I still think `*args` is simpler. That is what I did when I explored creating a similar package.
Though this is a different implementation, it shows how `mutate` could work.

``` python
from ggplot import *
from ggplot.data import *
import pandas as pd
import numpy as np
from patsy.eval import EvalEnvironment

class DataFrameOperator(object):
    env = None

    def __init__(self, *args, **kwargs):
        # Prevent duplicate captures of the
        # same environment
        if not self.env:
            self.env = EvalEnvironment.capture(1)

    def __rrshift__(self, other):
        if isinstance(other, pd.DataFrame):
            self.data = other
        elif isinstance(other, DataFrameOperator):
            self.data = other.data
        else:
            raise TypeError('Unknown type')

        return self.run()

    def run(self):
        return self.data


class mutate(DataFrameOperator):
    def __init__(self, *args, **kwargs):
        super(mutate, self).__init__(*args, **kwargs)
        cols = [col for col, expr in args]
        exprs = [expr for col, expr in args]
        self.columns = cols + list(kwargs.keys())
        self.expressions = exprs + list(kwargs.values())

    def run(self):
        env = self.env.with_outer_namespace(self.data)
        for col, expr in zip(self.columns, self.expressions):
            value = env.eval(expr)
            self.data[col] = value
        return self.data


df = diamonds.head(20).copy()
res1 = df >> mutate(carat2='carat*2', carat3='carat.round()')
res2 = df >> mutate(('carat2', 'carat*2'), ('carat3', 'carat2.round()'))
res2
```
