### ISSUE TITLE
anti_join operation request

### ISSUE THREAD

**Issue by antvalencia** [dodger487/dplython#72]
An enhancement request (if you are taking these) for an [anti_join operation](http://zevross.com/blog/2014/08/05/using-the-r-function-anti_join-to-find-unmatched-records/) over multiple columns.

**Comment by dodger487** [comment]
This should be done in the next few days-- just need to review #70. @bleearmstrong has been doing a great job implementing joins. 

We are definitely taking enhancement requests-- looking for suggestions, comments, criticisms, everything really.

**Comment by dodger487** [comment]
`anti_join` is now available, as of 8c9e2239bc635835d0e582e8435097644280d2c4
