### ISSUE TITLE
Or condition in sift()

### ISSUE THREAD

**Issue by guocheng** [dodger487/dplython#87]
I tried these two commands and they produce different output:

```
df >> sift(X.a == 1) 
df >> sift(X.a == 1 or X.b == 1) # this is equivalent to the line above

df >>sift(X.a == 1 | X.b == 1) # produces different results than the lines above and I don't know what the result represents
```

So is it possible to use the or condition inside sift at the moment?

**Comment by dodger487** [comment]
Hi! Right now "or" dies not work add you might expect. This should probably
throw an error. It is similar to if you tried to use "or" with pandas
series. Also like pandas series,  pipe | should give you the desired result.

**Comment by guocheng** [comment]
Hi Chris,

Really appreciate your work on dplython and your comment.

The problem that I am having right now is that with this statement:

```
dfr[(dfr.q5==1) | (dfr.q5==3)]  # I get 1479 rows
```

but with this:

```
dfr >> sift(X.q5==1 | X.q5==3) # I only get 265 rows
```

Am I not using sift correctly?

---

P.S. I want to help out with the documentation if possible.

**Comment by dodger487** [comment]
Hi Guo,
Thanks so much for using dplython and helping us out by filing an issue! My guess is the problem is parenthesis.

``` python
dfr >> sift((X.q5==1) | (X.q5==3))
```

I would imagine that if you removed some parentheses from the pandas version you would also get 265 rows.

``` python
dfr[dfr.q5==1 | dfr.q5==3]  # 265 rows?
```

If this example doesn't work, it will be easier for me to debug if you use a public dataset (like `diamonds` from the package).

**Comment by guocheng** [comment]
Hi Chris,

You are absolutely correct, I should've added brackets around the conditions.

In terms of documentation, what can I do to help？

**Comment by dodger487** [comment]
We'd love your help with documentation! Take a look at issue #21. There are a number of suggestions I have in there. If something looks good, please go for it and submit a pull request. If you have questions, please ask them on that issue and I'll try to respond as quickly as possible.
