### ISSUE TITLE
Unsupported Operand Types

### ISSUE THREAD

**Issue by souvikjana1993** [dodger487/dplython#94]
I get this error 
----> 1 df >> select(X.Month) >> head(5)

TypeError: unsupported operand type(s) for >>: 'DataFrame' and 'function'

**Comment by dodger487** [comment]
This error crops up when you haven't cast your DataFrame into a `DplyFrame`.
Try 
```
df = DplyFrame(df)
df >> select(X.Month) >> head(5)
```
