### ISSUE TITLE
dplyr::rename?

### ISSUE THREAD

**Issue by durrantmm** [dodger487/dplython#98]
The dplyr select() function is nice because you can simultaneously select and rename columns. Do you offer this functionality? Alternatively, implementing the function dplyr::rename() would be sufficient.

**Comment by dodger487** [comment]
We don't have this functionality currently but it shouldn't be too hard to
add. The main weird thing is that you would not be able to mix columns
you're renaming with columns you aren't, due to how Python function
definitions work.

**Comment by dodger487** [comment]
the "rename" function does currently exist within dplython
