### ISSUE TITLE
connecting to database using pyodbc

### ISSUE THREAD

**Issue by am2222** [dodger487/dplython#99]
Hi,
I was wondering to see how it is possible to connect to database and run queries using dplython, Is it even possible? Since dplyr library has this ability to make queries and run them using odbc

**Comment by dodger487** [comment]
No, we don't have that capability. It would be very cool but a significant
amount of work.

**Comment by am2222** [comment]
@dodger487 Yes exactly, because I guess such support will be a game changes in python scientific approach.
